name: SmartHoppers
version: ${version}
main: org.notionsmp.smarthoppers.SmartHoppers
api-version: '1.21'
load: POSTWORLD
author: "Akis (discord: yeahakis)"
dependencies:
  server:
    Nexo:
      load: BEFORE
      required: false